n=int(input("Enter the range:"))
lst=[]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       for i in range(0,n+1):
    if(i%2!=0):
        odd=i
        lst.append(odd)

print("Final",lst)

